### ISSUE TITLE
Contentful CMS with svelte-add graphql.

### ISSUE THREAD

**Issue by EdwinFdoGarcia** [svelte-add/graphql#10]
I want to integrate SvelteKit to a Contentful CMS with svelte-add graphql.

it's possible!
Thanks

**Comment by babichjacob** [comment]
I don't know what Contentful is, but if they have an API you can query, you can indeed "repackage" it as a GraphQL API through your SvelteKit server.

**Comment by EdwinFdoGarcia** [comment]
Thanks! 
contentful.io is a headless cms that delivers its graphql api to integrate it into any framework.

**Comment by babichjacob** [comment]
You can already fetch from it without `svelte-add/graphql` then. This is for adding your own GraphQL server to your SvelteKit project, and not for integrating with an existing one.
