### ISSUE TITLE
type-graphql?

### ISSUE THREAD

**Issue by Suya1671** [svelte-add/graphql#2]
it would be cool if this supported type-graphql.

**Comment by babichjacob** [comment]
It should be supported already (I hope) because you drop in your own schema per the comments in `src/routes/_graphql/schema.ts`?

**Comment by babichjacob** [comment]
Oh, TypeGraphQL makes its schema asynchronously. I can fix this later.

**Comment by babichjacob** [comment]
Supported! There are comments in `src/routes/_graphql/schema.ts` about where to put TypeGraphQL's asynchronous schema building like from [`sapper-typescript-graphql-template`](https://github.com/babichjacob/sapper-typescript-graphql-template/blob/main/src/graphql/index.ts#L14)
